# docker-compose.yml (Versión Final con network_mode: host)
services:
  redis:
    image: redis:alpine
    restart: always
    network_mode: host # <-- AÑADIDO

  postgres:
    image: postgres:15-alpine
    restart: always
    network_mode: host # <-- AÑADIDO
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  auth-service:
    build: ./services/auth-service
    restart: on-failure
    network_mode: host # <-- AÑADIDO
    env_file:
      - ./.env
  
  restaurant-service:
    build: ./services/restaurant-service
    restart: on-failure
    network_mode: host # <-- AÑADIDO
    env_file:
      - ./.env

  payment-service:
    build: ./services/payment-service
    restart: on-failure
    network_mode: host # <-- AÑADIDO
    env_file:
      - ./.env

  pos-service:
    build: ./services/pos-service
    restart: on-failure
    network_mode: host # <-- AÑADIDO
    env_file:
      - ./.env
      
  pac-service:
    build: ./services/pac-service
    restart: on-failure
    network_mode: host # <-- AÑADIDO
    env_file:
      - ./.env
      
  api-gateway:
    build: ./api-gateway
    restart: always
    network_mode: host # <-- AÑADIDO
    env_file:
      - ./.env

volumes:
  postgres_data: