# ===================================================================
# 		  docker-compose.yml para Backend de NextFactura
# Arquitectura Robusta con Healthchecks y Dependencias Condicionales
# ===================================================================
# La directiva 'version' ya no es necesaria en las versiones modernas de Compose.

services:

  # --- Base de Datos PostgreSQL con Healthcheck ---
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Cache con Redis y Healthcheck ---
  redis:
    image: redis:alpine
    restart: always
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # --- API Gateway (Punto de Entrada Único) ---
  api-gateway:
    build: ./api-gateway
    restart: on-failure
    env_file: [".env"]
    ports:
      - "4000:8080" # El único puerto expuesto a Nginx en el host
    depends_on:
      - auth-service
      - restaurant-service
      - payment-service
      - pos-service
      - pac-service
      - connector-service
      - notification-service # <-- DEPENDENCIA AÑADIDA
    networks:
      - app-net
  
  # --- Microservicios de la Aplicación ---
  auth-service:
    build: ./services/auth-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-net

  restaurant-service:
    build: ./services/restaurant-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net
    volumes:
      # Volumen para los archivos fiscales (CSD) y logos
      - /home/servidor/secure_uploads:/app/secure_uploads

  payment-service:
    build: ./services/payment-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net

  pos-service:
    build: ./services/pos-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        condition: service_healthy
      restaurant-service:
        condition: service_started
      connector-service:
        condition: service_started
    networks:
      - app-net
      
  pac-service:
    build: ./services/pac-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        condition: service_healthy
      restaurant-service:
        condition: service_started
    networks:
      - app-net
      
  connector-service:
    build: ./services/connector-service
    restart: on-failure
    env_file: [".env"]
    ports:
      # Puerto público para los agentes de escritorio
      - "4006:4006"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net

  # --- NUEVO SERVICIO DE NOTIFICACIONES ---
  notification-service:
    build: ./services/notification-service
    restart: on-failure
    env_file: [".env"]
    networks:
      - app-net
      
# --- Definición de la Red y el Volumen ---
volumes:
  postgres_data:
    driver: local

networks:
  app-net:
    driver: bridge