# ===================================================================
# 		  docker-compose.yml para Backend de NextFactura
# Arquitectura Robusta con Healthchecks y Dependencias Condicionales
# ===================================================================
version: '3.8'

services:

  # --- Base de Datos PostgreSQL con Healthcheck ---
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    healthcheck:
      # Este comando verifica si la base de datos está lista para aceptar conexiones.
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Cache con Redis y Healthcheck ---
  redis:
    image: redis:alpine
    restart: always
    networks:
      - app-net
    healthcheck:
      # Este comando verifica si Redis está respondiendo.
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # --- API Gateway ---
  api-gateway:
    build: ./api-gateway
    restart: on-failure
    env_file: [".env"]
    ports:
      # El único servicio que expone un puerto al host de Ubuntu.
      - "4000:8080"
    depends_on:
      # El gateway espera a que los demás servicios al menos hayan arrancado.
      - auth-service
      - restaurant-service
      - payment-service
      - pos-service
      - pac-service
    networks:
      - app-net
  
  # --- Microservicios con Dependencias Saludables ---
  auth-service:
    build: ./services/auth-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        # <-- CAMBIO CLAVE: No arranca hasta que postgres esté "saludable".
        condition: service_healthy
      redis:
        # <-- CAMBIO CLAVE: No arranca hasta que redis esté "saludable".
        condition: service_healthy
    networks:
      - app-net

  restaurant-service:
    build: ./services/restaurant-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        # <-- CAMBIO CLAVE: No arranca hasta que postgres esté "saludable".
        condition: service_healthy
    networks:
      - app-net

  payment-service:
    build: ./services/payment-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        # <-- CAMBIO CLAVE: No arranca hasta que postgres esté "saludable".
        condition: service_healthy
    networks:
      - app-net

  pos-service:
    build: ./services/pos-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        # <-- CAMBIO CLAVE: No arranca hasta que postgres esté "saludable".
        condition: service_healthy
      restaurant-service:
        condition: service_started
    networks:
      - app-net
      
  pac-service:
    build: ./services/pac-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        # <-- CAMBIO CLAVE: No arranca hasta que postgres esté "saludable".
        condition: service_healthy
      restaurant-service:
        condition: service_started
    networks:
      - app-net
      
# --- Definición de la Red y el Volumen ---
volumes:
  postgres_data:
    driver: local

networks:
  app-net:
    driver: bridge