# docker-compose.yml
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # IMPORTANTE: Cambia la ruta de la izquierda a la ubicación real de la carpeta 'build' de tu frontend.
      - /home/servidor/nextfactura-frontend/build:/var/www/frontend:ro
      # Monta los certificados SSL para que Nginx pueda usarlos para HTTPS.
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-net
    depends_on:
      - auth-service
      - restaurant-service
      - payment-service
      - pos-service
      - pac-service

  redis:
    image: redis:alpine
    restart: always
    networks:
      - app-net

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
  
  auth-service:
    build: ./services/auth-service
    restart: on-failure
    env_file: [".env"]
    volumes:
      - ./logs/auth-service:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - app-net

  restaurant-service:
    build: ./services/restaurant-service
    restart: on-failure
    env_file: [".env"]
    volumes:
      - ./logs/restaurant-service:/app/logs
    depends_on:
      - postgres
    networks:
      - app-net

  payment-service:
    build: ./services/payment-service
    restart: on-failure
    env_file: [".env"]
    volumes:
      - ./logs/payment-service:/app/logs
    depends_on:
      - postgres
    networks:
      - app-net

  pos-service:
    build: ./services/pos-service
    restart: on-failure
    env_file: [".env"]
    volumes:
      - ./logs/pos-service:/app/logs
    depends_on:
      - postgres
      - restaurant-service
    networks:
      - app-net
      
  pac-service:
    build: ./services/pac-service
    restart: on-failure
    env_file: [".env"]
    volumes:
      - ./logs/pac-service:/app/logs
    depends_on:
      - postgres
      - restaurant-service
    networks:
      - app-net
      
# --- Definición de la Red y el Volumen ---
volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge