# ===================================================================
# 		  docker-compose.yml para Backend de NextFactura
# Arquitectura:
# - Todos los servicios corren en una red privada (app-net).
# - Solo el API Gateway expone un puerto al exterior (al servidor Ubuntu).
# - La base de datos guarda sus datos en un volumen para persistencia.
# - Nginx NO está aquí. Se maneja por separado en el host de Ubuntu.
# ===================================================================
version: '3.8'

services:

  # --- Base de Datos PostgreSQL ---
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Volumen para que los datos de la BD no se borren al detener el contenedor.
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Cache con Redis ---
  redis:
    image: redis:alpine
    restart: always
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # --- API Gateway (Único punto de entrada al backend) ---
  api-gateway:
    build: ./api-gateway # Asegúrate que esta es la ruta correcta
    restart: on-failure
    env_file: [".env"]
    ports:
      # El único servicio que expone un puerto al host de Ubuntu.
      # El Nginx de Ubuntu se conectará a este puerto.
      - "4000:8080"
    depends_on:
      - auth-service
      - restaurant-service
      - payment-service
      - pos-service
      - pac-service
    networks:
      - app-net

  # --- Microservicios Internos (No exponen puertos) ---
  auth-service:
    build: ./services/auth-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-net

  restaurant-service:
    build: ./services/restaurant-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net

  payment-service:
    build: ./services/payment-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net

  pos-service:
    build: ./services/pos-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        condition: service_healthy
      restaurant-service:
        condition: service_started # o service_healthy si tiene healthcheck
    networks:
      - app-net
      
  pac-service:
    build: ./services/pac-service
    restart: on-failure
    env_file: [".env"]
    depends_on:
      postgres:
        condition: service_healthy
      restaurant-service:
        condition: service_started # o service_healthy si tiene healthcheck
    networks:
      - app-net
      
# --- Definición de la Red y el Volumen ---
volumes:
  postgres_data:
    driver: local

networks:
  app-net:
    driver: bridge